### ISSUE TITLE
Visualizations Feedback!

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/mds522_305#54]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [x] Great job adding figure numbers and captions! Though your captions could have been a bit more informative, overall this is a very good practice
- General comment about figures:
   - - [x] The sizes of Figure 1-3 are vastly disproportionate to the report, they're too tall and also possibly too tall. 
	- - [x] Consider removing the grey background (reminder: + theme_bw())
	- - [x] Stacked bar charts are probably not appropriate here. The question you should be asking yourself is what do you want to extract from this plot? I can give you suggestions of you can answer this question
	- - [x] You should probably arrange these plots in a grid so they take up less space 
- - [x] Suggest you use kable and kableExtra packages to format your tables a bit nicer
- I think the suggestions above will really help overall readability and flow of your final report so you can showcase your methods, analysis, and conclusions!

**Comment by evelynmoorhouse** [comment]
applied all feedback
